name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
exclude-labels:
    - 'duplicate'
    - 'invalid'
    - 'wontfix'
    - 'release'
exclude-contributors:
    - 'dependabot'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&`#@'
version-resolver:
    minor:
        labels:
            - 'feature request'
            - 'release'
    patch:
        labels:
            - 'technical debt'
            - 'bug'
            - 'translation'
    default: patch
template: |
    [Upgrade Kimai](https://www.kimai.org/documentation/updates.html) - [Install Kimai](https://www.kimai.org/documentation/installation.html) - [Docker](https://www.kimai.org/documentation/docker.html)

    **Compatible with PHP 8.1 to 8.3**
    
    $CHANGES
    
    Involved in this release: $CONTRIBUTORS - thank you!
