monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [403, 404]
        nested:
            type: stream
            level: info
            path: "%kernel.logs_dir%/%kernel.environment%.log"

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
